spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public_key.pem
  profiles:
    default: dev

data:
  init:
    password: ${LOGIN_PASSWORD}

jwt:
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  security:
    private-key-location: classpath:keys/private_key.pem

server:
  port: ${PORT:8080}